server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:../h2-db/issue_data;MODE=MYSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: sa  #????????
    password: sa  #???????
  sql:
    init:
#      schema-locations: classpath:sql/h2/schema.sql
#    data: classpath:sql/h2/data.sql